import type { Capability } from "./capability";
import { OPENAI_FIRSTPARTY_QUIRKS, OPENAI_REASONING_QUIRKS } from "./quirks";

export type CatalogPlugin =
  | "anthropic"
  | "openai"
  | "openai-compatible"
  | "google-genai";

export type DiscoverySource = {
  // The discovery support-matrix provider name (e.g. "opencode-zen"), not the
  // catalog provider name or the plugin.
  provider: string;
  // The exact wire model id the matrix probed (e.g. "kimi-k3").
  model: string;
};

export type CatalogOfferingSpec = {
  // References a CatalogModelSpec.canonicalName.
  model: string;
  // Lower is preferred first when several deployments serve one model.
  priority: number;
  // The (provider, model) whose wire capabilities this offering's baked
  // `capabilities` are drawn from in the discovery support matrix, or null when
  // this exact tuple has not been probed. Kept alongside the baked list as
  // provenance: the guard recomputes from this tuple and asserts the baked
  // value still matches.
  discoverySource: DiscoverySource | null;
  // Model capabilities the discovery matrix cannot prove (long-context,
  // prompt-caching), curated by hand. Kept as provenance for the baked list.
  curatedCapabilities: Capability[];
  // The resolved capabilities this offering advertises: the matrix wire set for
  // `discoverySource` (empty when null) followed by `curatedCapabilities`,
  // baked to a literal so importing the catalog pulls no discovery rig. The
  // guard test re-bakes from the provenance above and fails if this drifts.
  capabilities: Capability[];
  // Per-deployment adapter accommodations, explicit on every offering even when
  // empty. See OPENAI_REASONING_QUIRKS for why the opencode-zen reasoning
  // offerings carry explicit reasoning quirks.
  quirks: Record<string, unknown>;
};

export type CatalogProviderSpec = {
  name: string;
  plugin: CatalogPlugin;
  baseURL: string;
  offerings: CatalogOfferingSpec[];
};

// Several models are offered by more than one provider: `kimi-k3` across the
// Fireworks / Moonshot / OpenRouter relays, `kimi-k2.6` across those three plus
// the two OpenCode Zen relays, and `kimi-k2.7-code` across the two OpenCode Zen
// relays. Distinct
// priorities give source resolution a deterministic order across the
// deployments of a shared model. The anthropic and google-genai adapters carry
// no accommodations, so those offerings ship an empty quirks bag. OpenAI Direct
// serves gpt-5.x, which rejects `max_tokens`, so it carries
// OPENAI_FIRSTPARTY_QUIRKS. The openai-compatible relay offerings that advertise
// reasoning carry OPENAI_REASONING_QUIRKS; gpt-5.4-mini, which advertises only
// structured output, ships an empty bag.
export const catalogProviders: CatalogProviderSpec[] = [
  {
    name: "Anthropic Direct",
    plugin: "anthropic",
    baseURL: "https://api.anthropic.com",
    offerings: [
      {
        model: "claude-sonnet-5",
        priority: 0,
        discoverySource: { provider: "anthropic", model: "claude-sonnet-5" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "redacted-thinking",
          "redacted-thinking-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-opus-5",
        priority: 5,
        discoverySource: { provider: "anthropic", model: "claude-opus-5" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "redacted-thinking",
          "redacted-thinking-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-haiku-4-5-20251001",
        priority: 10,
        discoverySource: {
          provider: "anthropic",
          model: "claude-haiku-4-5-20251001",
        },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "redacted-thinking",
          "redacted-thinking-streaming",
        ],
        quirks: {},
      },
      {
        model: "claude-fable-5",
        priority: 15,
        discoverySource: { provider: "anthropic", model: "claude-fable-5" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-opus-4-8",
        priority: 20,
        discoverySource: { provider: "anthropic", model: "claude-opus-4-8" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-opus-4-5-20251101",
        priority: 25,
        discoverySource: {
          provider: "anthropic",
          model: "claude-opus-4-5-20251101",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-opus-4-6",
        priority: 30,
        discoverySource: { provider: "anthropic", model: "claude-opus-4-6" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-opus-4-7",
        priority: 35,
        discoverySource: { provider: "anthropic", model: "claude-opus-4-7" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-sonnet-4-5-20250929",
        priority: 40,
        discoverySource: {
          provider: "anthropic",
          model: "claude-sonnet-4-5-20250929",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "claude-sonnet-4-6",
        priority: 45,
        discoverySource: { provider: "anthropic", model: "claude-sonnet-4-6" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "reasoning-content",
          "reasoning-content-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "long-context",
        ],
        quirks: {},
      },
    ],
  },
  {
    name: "OpenAI Direct",
    plugin: "openai",
    baseURL: "https://api.openai.com/v1",
    offerings: [
      {
        model: "gpt-5.5",
        priority: 0,
        discoverySource: { provider: "openai", model: "gpt-5.5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.6-sol",
        priority: 5,
        discoverySource: { provider: "openai", model: "gpt-5.6-sol" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.6-terra",
        priority: 10,
        discoverySource: { provider: "openai", model: "gpt-5.6-terra" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.6-luna",
        priority: 15,
        discoverySource: { provider: "openai", model: "gpt-5.6-luna" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5",
        priority: 20,
        discoverySource: { provider: "openai", model: "gpt-5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5-mini",
        priority: 25,
        discoverySource: { provider: "openai", model: "gpt-5-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5-nano",
        priority: 30,
        discoverySource: { provider: "openai", model: "gpt-5-nano" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.1",
        priority: 35,
        discoverySource: { provider: "openai", model: "gpt-5.1" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.2",
        priority: 40,
        discoverySource: { provider: "openai", model: "gpt-5.2" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.4",
        priority: 45,
        discoverySource: { provider: "openai", model: "gpt-5.4" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.4-mini",
        priority: 50,
        discoverySource: { provider: "openai", model: "gpt-5.4-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-5.4-nano",
        priority: 55,
        discoverySource: { provider: "openai", model: "gpt-5.4-nano" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "o1",
        priority: 60,
        discoverySource: { provider: "openai", model: "o1" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "o3",
        priority: 65,
        discoverySource: { provider: "openai", model: "o3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "o3-mini",
        priority: 70,
        discoverySource: { provider: "openai", model: "o3-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "o4-mini",
        priority: 75,
        discoverySource: { provider: "openai", model: "o4-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4.1",
        priority: 80,
        discoverySource: { provider: "openai", model: "gpt-4.1" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4.1-mini",
        priority: 85,
        discoverySource: { provider: "openai", model: "gpt-4.1-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4.1-nano",
        priority: 90,
        discoverySource: { provider: "openai", model: "gpt-4.1-nano" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4o",
        priority: 95,
        discoverySource: { provider: "openai", model: "gpt-4o" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4o-mini",
        priority: 100,
        discoverySource: { provider: "openai", model: "gpt-4o-mini" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4-turbo",
        priority: 105,
        discoverySource: { provider: "openai", model: "gpt-4-turbo" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "document-input",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
      {
        model: "gpt-4",
        priority: 110,
        discoverySource: { provider: "openai", model: "gpt-4" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
        ],
        quirks: OPENAI_FIRSTPARTY_QUIRKS,
      },
    ],
  },
  {
    name: "Gemini Direct",
    plugin: "google-genai",
    baseURL: "https://generativelanguage.googleapis.com",
    offerings: [
      {
        model: "gemini-2.5-pro",
        priority: 0,
        discoverySource: { provider: "google-genai", model: "gemini-2.5-pro" },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "gemini-3.6-flash",
        priority: 5,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-3.6-flash",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "gemini-2.5-flash",
        priority: 10,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-2.5-flash",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "gemini-3.5-flash",
        priority: 15,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-3.5-flash",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "gemini-2.5-flash-image",
        priority: 20,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-2.5-flash-image",
        },
        curatedCapabilities: [],
        capabilities: ["image-output", "image-output-streaming"],
        quirks: {},
      },
      {
        model: "gemini-3.1-flash-image",
        priority: 25,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-3.1-flash-image",
        },
        curatedCapabilities: [],
        capabilities: ["image-output", "image-output-streaming"],
        quirks: {},
      },
      {
        model: "gemini-3-flash-preview",
        priority: 30,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-3-flash-preview",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
      {
        model: "gemini-3.1-pro-preview",
        priority: 35,
        discoverySource: {
          provider: "google-genai",
          model: "gemini-3.1-pro-preview",
        },
        curatedCapabilities: ["long-context"],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling-multi-turn",
          "function-calling-multi-turn-streaming",
          "function-calling-with-thinking",
          "function-calling-with-thinking-streaming",
          "vision-input",
          "vision-input-streaming",
          "audio-input",
          "audio-input-streaming",
          "video-input",
          "video-input-streaming",
          "document-input",
          "document-input-streaming",
          "code-execution",
          "code-execution-streaming",
          "grounding",
          "grounding-streaming",
          "files-api-reference",
          "files-api-reference-streaming",
          "structured-output",
          "structured-output-streaming",
          "long-context",
        ],
        quirks: {},
      },
    ],
  },
  {
    name: "Fireworks Kimi",
    plugin: "openai-compatible",
    baseURL: "https://api.fireworks.ai/inference/v1",
    offerings: [
      {
        model: "kimi-k3",
        priority: 0,
        discoverySource: { provider: "opencode-zen", model: "kimi-k3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "kimi-k2.6",
        priority: 0,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.6" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
    ],
  },
  {
    name: "Moonshot Kimi",
    plugin: "openai-compatible",
    baseURL: "https://api.moonshot.ai/v1",
    offerings: [
      {
        model: "kimi-k3",
        priority: 10,
        discoverySource: { provider: "opencode-zen", model: "kimi-k3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "kimi-k2.6",
        priority: 5,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.6" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
    ],
  },
  {
    name: "OpenRouter Kimi",
    plugin: "openai-compatible",
    baseURL: "https://openrouter.ai/api/v1",
    offerings: [
      {
        model: "kimi-k3",
        priority: 20,
        discoverySource: { provider: "opencode-zen", model: "kimi-k3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "kimi-k2.6",
        priority: 10,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.6" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
    ],
  },
  {
    name: "OpenCode Zen v1",
    plugin: "openai-compatible",
    baseURL: "https://opencode.ai/zen/v1",
    offerings: [
      {
        model: "kimi-k2.7-code",
        priority: 0,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.7-code" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "kimi-k2.6",
        priority: 15,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.6" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "qwen3.7-plus",
        priority: 5,
        discoverySource: { provider: "opencode-zen", model: "qwen3.7-plus" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "mimo-v2.5",
        priority: 10,
        discoverySource: { provider: "opencode-zen", model: "mimo-v2.5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "glm-5.2",
        priority: 20,
        discoverySource: { provider: "opencode-zen", model: "glm-5.2" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "gpt-5.4-mini",
        priority: 25,
        discoverySource: { provider: "opencode-zen", model: "gpt-5.4-mini" },
        curatedCapabilities: [],
        capabilities: ["structured-output", "structured-output-streaming"],
        quirks: {},
      },
      {
        model: "glm-5",
        priority: 30,
        discoverySource: { provider: "opencode-zen", model: "glm-5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "glm-5.1",
        priority: 35,
        discoverySource: { provider: "opencode-zen", model: "glm-5.1" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "hy3",
        priority: 40,
        discoverySource: { provider: "opencode-zen", model: "hy3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: {},
      },
      {
        model: "kimi-k2.5",
        priority: 45,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "mimo-v2.5-pro",
        priority: 50,
        discoverySource: { provider: "opencode-zen", model: "mimo-v2.5-pro" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: {},
      },
      {
        model: "minimax-m2.5",
        priority: 55,
        discoverySource: { provider: "opencode-zen", model: "minimax-m2.5" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: {},
      },
      {
        model: "minimax-m2.7",
        priority: 60,
        discoverySource: { provider: "opencode-zen", model: "minimax-m2.7" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: {},
      },
      {
        model: "minimax-m3",
        priority: 65,
        discoverySource: { provider: "opencode-zen", model: "minimax-m3" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
        ],
        quirks: {},
      },
      {
        model: "qwen3.5-plus",
        priority: 70,
        discoverySource: { provider: "opencode-zen", model: "qwen3.5-plus" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "qwen3.6-plus",
        priority: 75,
        discoverySource: { provider: "opencode-zen", model: "qwen3.6-plus" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "qwen3.7-max",
        priority: 80,
        discoverySource: { provider: "opencode-zen", model: "qwen3.7-max" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "qwen3.8-max",
        priority: 85,
        discoverySource: { provider: "opencode-zen", model: "qwen3.8-max" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
    ],
  },
  {
    name: "OpenCode Zen Go v1",
    plugin: "openai-compatible",
    baseURL: "https://opencode.ai/zen/go/v1",
    offerings: [
      {
        model: "kimi-k2.7-code",
        priority: 10,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.7-code" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "kimi-k2.6",
        priority: 20,
        discoverySource: { provider: "opencode-zen", model: "kimi-k2.6" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "vision-input",
          "reasoning-content",
          "reasoning-content-streaming",
          "structured-output",
          "structured-output-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "deepseek-v4-pro",
        priority: 0,
        discoverySource: { provider: "opencode-zen", model: "deepseek-v4-pro" },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
      {
        model: "deepseek-v4-flash",
        priority: 5,
        discoverySource: {
          provider: "opencode-zen",
          model: "deepseek-v4-flash",
        },
        curatedCapabilities: [],
        capabilities: [
          "plain-text",
          "plain-text-streaming",
          "function-calling",
          "function-calling-multi-turn",
          "reasoning-content",
          "reasoning-content-streaming",
        ],
        quirks: OPENAI_REASONING_QUIRKS,
      },
    ],
  },
];
